name: flutter_sendbird
description: Integration with Sendbird iOS and Android SDKs
version: 0.0.7
author:
homepage: https://github.com/sensestar/flutter_sendbird
repository: https://github.com/sensestar/flutter_sendbird

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  http: ^0.12.0+2
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  build_runner: ^1.11.5

flutter:
  plugin:
    platforms:
      android:
        package: com.sstar.flutter_sendbird
        pluginClass: FlutterSendbirdPlugin
      ios:
        pluginClass: FlutterSendbirdPlugin
